name: On push

on:
  push:
    branches:
      - next

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn tsc
      - name: Tests
        run: yarn test:ci
      - name: Lint
        run: yarn lint:ci

  upload-build:
    name: Upload build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Build all
        run: yarn build
      - name: Upload build
        run: yarn ts-node src/cli/src/bin.ts upload-build -c demo/build-tracker-cli.config.js -b next
        env:
          BT_API_AUTH_TOKEN: ${{ secrets.BT_API_AUTH_TOKEN }}

  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Build docs
        run: yarn workspace @build-tracker/docs build
      - name: Deploy documentation
        uses: paularmstrong/docusaurus-github-action@master
        env:
          BUILD_DIR: docs/website
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          PROJECT_NAME: build-tracker
